BFI.WebAdmin/Models/LocationViewModels.cs
using BFI.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BFI.WebAdmin.Models {
    public abstract class BaseLocationViewModel {
        public string AttachmentUri { get; set; }
    }
    public class LocationViewModel : BaseLocationViewModel {

        public Location Location { get; set; }
            
    }
    public class LocationsViewModel : BaseLocationViewModel {
        public List<Location> Locations { get; set; }
    }

    public class CreateLocationViewModel : BaseLocationViewModel {
        public Location Location { get; set; }
        public List<SelectListItem> AllCountries { get; set; }

    }

    public class EditLocationViewModel : BaseLocationViewModel {
        public Location Location { get; set; }
        public List<SelectListItem> AllCountries { get; set; }
    }
}

BFI.WebAdmin/Controllers/LocationsController.cs
using BFI.Core.Constants;
using BFI.Core.Extensions;
using BFI.Entities;
using BFI.WebAdmin.Models;
using BFI.WebAdmin.Repositories;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Linq;
using System.Threading.Tasks;

namespace BFI.WebAdmin.Controllers {
    
    public class LocationsController : BaseController {
        private LocationRepository repo;
        private UserRepository usersRepo;


        public LocationsController(LocationRepository repo, UserRepository usersRepo, CountryRepository countryRepo, IConfiguration configuration) : base(countryRepo, configuration) {
            this.repo = repo;
            this.usersRepo = usersRepo;
        }
        [Authorize(Policy = PermissionNames.LocationsView)]
        public async Task<IActionResult> Index() {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);

            var model = new LocationsViewModel();
            if (User.HasRole(RoleNames.BFIAdministrator)) {
                model.Locations = await repo.GetAll(accessToken);
            } else {
                model.Locations = await repo.GetMy(accessToken);
            }

            return View(model);
        }
        [Authorize(Policy = PermissionNames.LocationsView)]
        public async Task<IActionResult> View(int id) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var location = await repo.Get(accessToken, id);

            if(location == null) {
                return NotFound();
            }
            var model = new LocationViewModel();
            model.Location = location;
            model.AttachmentUri = LocationAttachmentUri;
            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = PermissionNames.LocationsCreate)]
        public async Task<IActionResult> Create() {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);

            var viewModel = new CreateLocationViewModel();
            viewModel.Location = new Entities.Location();

            viewModel.AllCountries = await base.Countries(accessToken);
            viewModel.Location.CountryId = int.Parse(viewModel.AllCountries.Where(f => f.Text == "United States").FirstOrDefault().Value);
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Policy = PermissionNames.LocationsCreate)]
        public async Task<IActionResult> Create([FromForm] Location location) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);

            if (!ModelState.IsValid) {
                var viewModel = new CreateLocationViewModel();
                viewModel.Location = location;

                viewModel.AllCountries = await base.Countries(accessToken);

                return View(viewModel);
            }

            var ret = await repo.Create(accessToken, location);

            return RedirectToAction(nameof(View), new { id = ret.Id });
        }

        [HttpGet]
        [Authorize(Policy = PermissionNames.LocationsUpdate)]
        public async Task<IActionResult> Edit(int id) {
            var viewModel = new EditLocationViewModel();
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);

            viewModel.Location = await repo.Get(accessToken, id);
            if (viewModel.Location == null) {
                return NotFound();
            }
            viewModel.AllCountries = await base.Countries(accessToken);
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Policy = PermissionNames.LocationsUpdate)]
        public async Task<IActionResult> Update([FromRoute] int id, [FromForm] Location location) {
            if (!ModelState.IsValid) {
                var viewModel = new EditLocationViewModel();
                viewModel.Location = location;
                return View("Edit", viewModel);
            }
            location.Id = id;

            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var ret = await repo.Update(accessToken, location);

            return RedirectToAction(nameof(Edit), new { id = ret.Id });
        }

        [HttpPost]
        [Authorize(Policy = PermissionNames.LocationsDelete)]
        public async Task<IActionResult> Delete(int id) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var result = await repo.Delete(accessToken, id);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize(Policy = PermissionNames.LocationsUpdate)]
        public async Task<IActionResult> CreateAttachment([FromRoute] int id, string Description, IFormFile file) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);

            await repo.CreateAttachment(accessToken, id, file, Description);

            return RedirectToAction(nameof(Edit), new { id = id });
        }

        [HttpPost]
        [Authorize(Policy = PermissionNames.LocationsDelete)]
        public async Task<IActionResult> DeleteAttachment(int id, int attachmentId) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var result = await repo.DeleteAttachment(accessToken, id, attachmentId);

            return RedirectToAction(nameof(Edit), new { id = id });
        }
    }
}

BFI.WebAdmin/Views/Locations/Create.cshtml
@model BFI.WebAdmin.Models.CreateLocationViewModel
<h1>Create a New Location</h1>
<form asp-controller="Locations" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Location.Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.Name" class="form-control" />
            <span asp-validation-for="Location.Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Type" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select class="form-control" asp-for="@Model.Location.Type" asp-items="Html.GetEnumSelectList(typeof(BFI.Entities.LocationType))"></select>
            <span asp-validation-for="Location.Type" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Address" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.Address" class="form-control" />
            <span asp-validation-for="Location.Address" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.City" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.City" class="form-control" />
            <span asp-validation-for="Location.City" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.StateProvince" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.StateProvince" class="form-control" />
            <span asp-validation-for="Location.StateProvince" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.PostCode" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.PostCode" class="form-control" />
            <span asp-validation-for="Location.PostCode" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Country" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select class="form-control" asp-for="@Model.Location.CountryId" asp-items="Model.AllCountries"></select>
            <span asp-validation-for="Location.CountryId" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Excerpt" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.Excerpt" class="form-control" />
            <span asp-validation-for="Location.Excerpt" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Description" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.Description" class="form-control" />
            <span asp-validation-for="Location.Description" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Latitude" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.Latitude" class="form-control" readonly />
            <span asp-validation-for="Location.Latitude" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Longitude" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.Longitude" class="form-control" readonly />
            <span asp-validation-for="Location.Longitude" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Location.PinUri" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.PinUri" class="form-control" />
            <span asp-validation-for="Location.PinUri" class="text-danger"></span>
        </div>
    </div>
    <input type="submit" class="btn btn-success" value="Create" />
</form>

<div id="map" style="width:100%;height:640px;"></div>

<a asp-area="" asp-controller="Locations" asp-action="Index" title="Locations" class="btn btn-primary">Back</a>
@section Scripts{
    <script>
        var map;
        var marker;
        function initMap() {
            map = new google.maps.Map(document.getElementById('map'), {
                zoom: 12,
                center: new google.maps.LatLng(44, -110),
            });

            google.maps.event.addListener(map, 'click', function (event) {
                $("#Location_Latitude").val(event.latLng.lat());
                $("#Location_Longitude").val(event.latLng.lng());
                placeMarker(event.latLng);
            });

            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };

                    map.setCenter(pos);
                }, function () {
                    handleLocationError(true, infoWindow, map.getCenter());
                });
            } else {
                // Browser doesn't support Geolocation
                handleLocationError(false, infoWindow, map.getCenter());
            }
        }

        function placeMarker(location) {
            if (marker) {
                marker.setPosition(location);
            } else {
                marker = new google.maps.Marker({
                    position: location,
                    map: map
                });
            }
        }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=@ViewData["googleMapsApiKey"]&callback=initMap" async defer></script>
}

BFI.WebAdmin/Views/Locations/Edit.cshtml
@model BFI.WebAdmin.Models.EditLocationViewModel
<h1>Edit Location</h1>
<form asp-controller="Locations" asp-action="Update" method="post" asp-route-id="@Model.Location.Id">
    <div class="form-group">
        <label asp-for="Location.Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.Name" class="form-control" />
            <span asp-validation-for="Location.Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Type" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select class="form-control" asp-for="@Model.Location.Type" asp-items="Html.GetEnumSelectList(typeof(BFI.Entities.LocationType))"></select>
            <span asp-validation-for="Location.Type" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Address" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.Address" class="form-control" />
            <span asp-validation-for="Location.Address" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.City" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.City" class="form-control" />
            <span asp-validation-for="Location.City" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.StateProvince" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.StateProvince" class="form-control" />
            <span asp-validation-for="Location.StateProvince" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.PostCode" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.PostCode" class="form-control" />
            <span asp-validation-for="Location.PostCode" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Country" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select class="form-control" asp-for="@Model.Location.CountryId" asp-items="Model.AllCountries"></select>
            <span asp-validation-for="Location.CountryId" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Excerpt" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.Excerpt" class="form-control" />
            <span asp-validation-for="Location.Excerpt" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Description" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.Description" class="form-control" />
            <span asp-validation-for="Location.Description" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Latitude" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.Latitude" asp-format="{0:N14}" class="form-control" readonly />
            <span asp-validation-for="Location.Latitude" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location.Longitude" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.Longitude" asp-format="{0:N14}" class="form-control" readonly />
            <span asp-validation-for="Location.Longitude" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Location.PinUri" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Location.PinUri" class="form-control" />
            <span asp-validation-for="Location.PinUri" class="text-danger"></span>
        </div>
    </div>

    <input type="submit" class="btn btn-success" value="Update" />
    <a asp-area="" asp-controller="Locations" asp-action="Index" title="Locations" class="btn btn-primary">Back</a>
    <a asp-area="" asp-controller="Locations" asp-action="View" title="View" class="btn btn-info" asp-route-id="@Model.Location.Id">View</a>
</form>

<h2>Move around the location</h2>
<div id="map" style="width:100%;height:320px;"></div>

<h2>Attachments</h2>
<form method="post" enctype="multipart/form-data" asp-controller="Locations" asp-route-id="@Model.Location.Id" asp-action="CreateAttachment">
    <div class="form-group">
        <label class="col-md-2 control-label">Upload File</label>
        <div class="col-md-10">
            <input type="file" name="file" multiple class="form-control" required />
        </div>

    </div>
    <br />
    <div class="form-group">
        <label class="col-md-2 control-label">Description</label>
        <div class="col-md-10">
            <input name="Description" class="form-control" required />
        </div>
    </div>
    <div class="col-md-10">
        <input type="submit" value="Upload" />
    </div>
</form>

<table class="table table-striped table-bordered">
    <tr>
        <td>Name</td>
        <td>Type</td>
        <td>Description</td>
        @*<td>Uri</td>*@
        <td></td>
    </tr>
    @if(Model.Location != null && Model.Location.Attachments != null) {
        foreach(var item in Model.Location?.Attachments) {
    <tr>
        <td>@item.Name</td>
        <td>@item.Type.GetDisplayName()</td>
        <td>@item.Description</td>
        @*<td>@item.Uri</td>*@
        <td>
            @if(User.HasPermission(PermissionNames.LocationsDelete)) {
                <form style="display:inline-block" asp-controller="Locations" asp-action="DeleteAttachment" asp-route-id="@item.LocationId" asp-route-attachmentId="@item.Id" method="post">
                    <input type="submit" value="Remove" class="btn btn-danger delete" />
                </form>
            }
        </td>
    </tr>
        }
    }
</table>

@Html.Partial("_DeleteConfirmation")

@section Scripts{
    <script>
    var map;
    var marker;
    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            zoom: 18,
            center: new google.maps.LatLng(@Model.Location.Latitude, @Model.Location.Longitude),
        });
        marker = new google.maps.Marker({
            position: map.center,
            map: map
        });

        google.maps.event.addListener(map, 'click', function (event) {
            $("#Location_Latitude").val(event.latLng.lat());
            $("#Location_Longitude").val(event.latLng.lng());
            placeMarker(event.latLng);
        });
    }

    function placeMarker(location) {
        marker.setPosition(location);
    }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=@ViewData["googleMapsApiKey"]&callback=initMap" async defer></script>
}

BFI.WebAdmin/Views/Locations/Index.cshtml
@model BFI.WebAdmin.Models.LocationsViewModel
<h1>All Locations</h1>
<table class="table table-striped table-bordered">
    <tr>
        <td>Name</td>
        <td>Type</td>
        <td>Address</td>
        <td>City</td>
        <td>State / Province</td>
        <td>Post Code</td>
        <td>
            @if (User.HasPermission(PermissionNames.LocationsCreate)) {
                <a asp-area="" asp-controller="Locations" asp-action="Create" class="btn btn-success">Create</a>
            }
        </td>
    </tr>
    @foreach (var loc in Model.Locations) {
    <tr>
        <td>@loc.Name</td>
        <td>@loc.Type.GetDisplayName()</td>
        <td>@loc.Address</td>
        <td>@loc.City</td>
        <td>@loc.StateProvince</td>
        <td>@loc.PostCode</td>
        <td>
            @if (User.HasPermission(PermissionNames.LocationsView)) {
                <a asp-area="" asp-controller="Locations" asp-action="View" asp-route-id="@loc.Id" class="btn btn-info">View</a>
            }
            @if (User.HasPermission(PermissionNames.LocationsUpdate)) {
                <a asp-area="" asp-controller="Locations" asp-action="Edit" asp-route-id="@loc.Id" class="btn btn-primary">Edit</a>
            }
            @if (User.HasPermission(PermissionNames.LocationsDelete)) {
            <form style="display:inline-block" asp-controller="Locations" asp-action="Delete" asp-route-id="@loc.Id" method="post">
                <input type="button" value="Remove" class="btn btn-danger delete" />
            </form>
            }
        </td>
    </tr>
    }
</table>

@Html.Partial("_DeleteConfirmation")

BFI.WebAdmin/Views/Locations/View.cshtml
@model BFI.WebAdmin.Models.LocationViewModel
<h1>View Location</h1>

<a asp-area="" asp-controller="Locations" asp-action="Edit" asp-route-id="@Model.Location.Id" title="Edit" class="btn btn-success">Edit</a>
<a asp-area="" asp-controller="Locations" asp-action="Index" title="Locations" class="btn btn-primary">Back</a>

<div id="map" style="width:100%;height:640px;"></div>

@section Scripts{

    <script>
    var map;
    var marker;
    var infoWindow;
    var contentString = `@Html.Partial("_GoogleMapsInfoWIndow", Model)`;

    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            zoom: 18,
            center: new google.maps.LatLng(@Model.Location.Latitude, @Model.Location.Longitude),
        });

        marker = new google.maps.Marker({
            position: map.center,
            map: map
        });

        infoWindow = new google.maps.InfoWindow({ content: contentString });

        infoWindow.open(map, marker);
    }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=@ViewData["googleMapsApiKey"]&callback=initMap" async defer></script>
}