BFI.WebAdmin/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BFI.Core.Constants;
using BFI.Core.Extensions;
using BFI.Entities;
using BFI.WebAdmin.Models;
using BFI.WebAdmin.Repositories;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace BFI.WebAdmin.Controllers {
    
    public class CompaniesController : BaseController {
        private CompanyRepository repo;
        
        public CompaniesController(CompanyRepository repo, CountryRepository countryRepo, IConfiguration configuration) : base(countryRepo, configuration) {
            this.repo = repo;
        }

        [Authorize(Policy = PermissionNames.CompaniesView)]
        public async Task<IActionResult> Index() {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);

            var model = new CompaniesViewModel();
            if (User.HasRole(RoleNames.BFIAdministrator)) {
                model.Companies = await repo.GetAll(accessToken);
            } else {
                model.Companies = await repo.GetMy(accessToken);
            }

            return View(model);
        }
        [Authorize(Policy = PermissionNames.CompaniesView)]
        public async Task<IActionResult> View(int id) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var company = await repo.Get(accessToken, id);
            var companyUsers = await repo.UsersInCompany(accessToken, id);
            
            var model = new CompanyViewModel();
            model.Company = company;
            model.Users = companyUsers;
            
            return View(model);
        }
        
        [HttpPost]
        [Authorize(Policy = PermissionNames.CompaniesDelete)]
        public async Task<IActionResult> Delete(int id) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var result = await repo.Delete(accessToken, id);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize(Policy = PermissionNames.CompaniesCreate)]
        public IActionResult Create() {
            var viewModel = new CreateCompanyViewModel();
            viewModel.Company = new Entities.Company();

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Policy = PermissionNames.CompaniesCreate)]
        public async Task<IActionResult> Create([FromForm] Company company) {
            if (!ModelState.IsValid) {
                var viewModel = new CreateCompanyViewModel();
                viewModel.Company = company;
                return View(viewModel);
            }

            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var ret = await repo.Create(accessToken, company);

            return RedirectToAction(nameof(View), new { id = ret.Id });
        }

        [HttpGet]
        [Authorize(Policy = PermissionNames.CompaniesUpdate)]
        public async Task<IActionResult> Edit(int id) {
            var viewModel = new EditCompanyViewModel();
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);

            viewModel.Company = await repo.Get(accessToken, id);

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Policy = PermissionNames.CompaniesUpdate)]
        public async Task<IActionResult> Update([FromRoute] int id, [FromForm] Company company) {
            if (!ModelState.IsValid) {
                var viewModel = new EditCompanyViewModel();
                viewModel.Company = company;
                return View(viewModel);
            }
            company.Id = id;

            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var ret = await repo.Update(accessToken, company);

            return RedirectToAction(nameof(View), new { id = ret.Id });
        }
    }
}

BFI.WebAdmin/Controllers/RegionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BFI.Core.Constants;
using BFI.Entities;
using BFI.WebAdmin.Models;
using BFI.WebAdmin.Repositories;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace BFI.WebAdmin.Controllers {
    
    public class RegionsController : BaseController {
        private RegionRepository repo;
        private LocationRepository locationRepo;

        public RegionsController(RegionRepository repo, LocationRepository locationRepo, CountryRepository countryRepo, IConfiguration configuration) : base(countryRepo, configuration) {
            this.repo = repo;
            this.locationRepo = locationRepo;
        }
        [Authorize(Policy = PermissionNames.RegionsView)]
        public async Task<IActionResult> Index() {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var regions = await repo.GetAll(accessToken);

            var model = new RegionsViewModel();
            model.Regions = regions;

            return View(model);
        }
        [Authorize(Policy = PermissionNames.RegionsView)]
        public async Task<IActionResult> View(int id) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var region = await repo.Get(accessToken, id);

            var model = new RegionViewModel();
            model.Region = region;
            model.LocationViewModels = new List<LocationViewModel>();

            foreach (var item in region.RegionLocations) {
                model.LocationViewModels.Add(new LocationViewModel() { Location = item.Location, AttachmentUri = LocationAttachmentUri });
            }

            return View(model);
        }

        [Authorize(Policy = PermissionNames.RegionsCreate)]
        public IActionResult Create() {
            var model = new CreateRegionViewModel();
            model.Region = new Entities.Region() { InitialZoom = 12 };
            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = PermissionNames.RegionsCreate)]
        public async Task<IActionResult> Create([FromForm] Region region) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);

            if(!ModelState.IsValid) {
                var viewModel = new CreateRegionViewModel();
                viewModel.Region = region;
                return View(viewModel);
            }

            var ret = await repo.Create(accessToken, region);

            return RedirectToAction(nameof(View), new { id = ret.Id });
        }

        [HttpGet]
        [Authorize(Policy = PermissionNames.RegionsUpdate)]
        public async Task<IActionResult> Edit(int id) {
            var viewModel = new EditRegionViewModel();
            //var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var accessToken = await base.GetAccessToken();

            var myLocations = await locationRepo.GetMy(accessToken);
            viewModel.MyLocations = new List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem>();
            foreach(var item in myLocations) {
                viewModel.MyLocations.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem() { Text = item.Name, Value = item.Id.ToString() });
            }

            viewModel.MyLocations = viewModel.MyLocations.OrderBy(f => f.Text).ToList();

            viewModel.Region = await repo.Get(accessToken, id);

            foreach(var item in viewModel.Region.RegionLocations) {
                viewModel.LocationViewModels.Add(new LocationViewModel() { Location = item.Location, AttachmentUri = LocationAttachmentUri });
            }
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Policy = PermissionNames.RegionsUpdate)]
        public async Task<IActionResult> RemoveLocation(int id, int locationId) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var result = await repo.RemoveLocation(accessToken, id, locationId);

            return RedirectToAction(nameof(Edit), new { id = id });
        }

        [HttpPost]
        [Authorize(Policy = PermissionNames.RegionsUpdate)]
        public async Task<IActionResult> AddLocation(int id, int SelectedLocationId) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var result = await repo.AddLocation(accessToken, id, SelectedLocationId);

            return RedirectToAction(nameof(Edit), new { id = id });
        }

        [HttpPost]
        [Authorize(Policy = PermissionNames.RegionsUpdate)]
        public async Task<IActionResult> Update([FromRoute] int id, [FromForm] Region region) {
            if(!ModelState.IsValid) {
                var viewModel = new EditRegionViewModel();
                viewModel.Region = region;
                return View("Edit", viewModel);
            }
            region.Id = id;

            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var ret = await repo.Update(accessToken, region);

            return RedirectToAction(nameof(Edit), new { id = ret.Id });
        }
    }
}

BFI.WebAdmin/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BFI.Core.Constants;
using BFI.WebAdmin.Models;
using BFI.WebAdmin.Repositories;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BFI.WebAdmin.Controllers {
    [Authorize(Policy = PolicyNames.BFIAdmin)]
    public class RolesController : Controller {
        private RoleRepository repo;
        public RolesController(RoleRepository repo) {
            this.repo = repo;
        }

        public async Task<IActionResult> Index() {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var roles = await repo.GetAll(accessToken);

            var model = new RolesViewModel();
            model.Roles = roles;

            return View(model);
        }

        public async Task<IActionResult> View(int id) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var role = await repo.Get(accessToken, id);
            var usersInRole = await repo.UsersInRole(accessToken, id);
            var model = new RoleViewModel();
            model.Role = role;
            model.UsersInRole = usersInRole;
            return View(model);
        }
    }
}

BFI.WebAdmin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BFI.Core.Constants;
using BFI.Entities;
using BFI.WebAdmin.Models;
using BFI.WebAdmin.Repositories;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace BFI.WebAdmin.Controllers {
    [Authorize(Policy = PolicyNames.BFIAdmin)]
    public class UsersController : BaseController {
        private UserRepository repo;
        private RoleRepository rolesRepo;
        private CompanyRepository companyRepo;
        public UsersController(UserRepository repo, RoleRepository rolesRepo, CountryRepository countryRepo, CompanyRepository companyRepo, IConfiguration configuration) : base(countryRepo, configuration) {
            this.repo = repo;
            this.rolesRepo = rolesRepo;
            this.companyRepo = companyRepo;
        }

        public async  Task<IActionResult> Index() {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var users = await repo.GetAll(accessToken);

            var model = new UsersViewModel();
            model.Users = users;

            return View(model);
        }

        public async Task<IActionResult> View(int id) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var user = await repo.Get(accessToken, id);
            var usersRoles = await repo.UserRoles(accessToken, id);
            var userCompanies = await repo.UserCompanies(accessToken, id);
            var roles = await rolesRepo.GetAll(accessToken);
            var companies = await companyRepo.GetAll(accessToken);
            var model = new UserViewModel();
            model.User = user;
            model.UsersRoles = usersRoles;
            model.UsersCompanies = userCompanies;
            model.AllRoles = roles;
            model.AllCompanies = companies;
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddToRole(int id, [FromForm] int SelectedRoleId) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var ret = await repo.AddRole(accessToken, id, SelectedRoleId);
           
            return RedirectToAction("View", new { id = id });
        }
        [HttpPost]
        public async Task<IActionResult> RemoveRole(int id, [FromForm] int roleId) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var ret = await repo.RemoveRole(accessToken, id, roleId);
           
            return RedirectToAction("View", new { id = id });
        }

        [HttpPost]
        public async Task<IActionResult> AddToCompany(int id, [FromForm] int SelectedCompanyId) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var ret = await repo.AddCompany(accessToken, id, SelectedCompanyId);

            return RedirectToAction("View", new { id = id });
        }
        [HttpPost]
        public async Task<IActionResult> RemoveCompany(int id, [FromForm] int companyId) {
            var accessToken = await HttpContext.GetTokenAsync(TokenNames.AccessToken);
            var ret = await repo.RemoveCompany(accessToken, id, companyId);

            return RedirectToAction("View", new { id = id });
        }

    }
}

BFI.WebAdmin/Views/Shared/_DeleteConfirmation.cshtml
<div id="delete-confirm" title="Confirm" style="display:none;">
    <p>Are you sure?</p>
</div>

BFI.WebAdmin/Views/Shared/_GoogleMapsInfoWindow.cshtml
@model BFI.WebAdmin.Models.LocationViewModel
<div id="infoWindow">
    <h1>@Model.Location.Name</h1>
    <h2>@Model.Location.Excerpt</h2>
    <p>@Model.Location.Description</p>

    @if (Model.Location.Attachments.Count > 0) {
        <h4>Attachments</h4>

        var images = Model.Location.Attachments.Where(f => f.Type == BFI.Entities.AttachmentType.Image);
        if (images.Count() > 0) {
            <h3>Images</h3>
            @foreach (var item in images) {
                <img src="@string.Format("{0}/{1}_{2}",Model.AttachmentUri, item.Id,item.Name)" alt="@item.Description" style="max-height:250px;max-width:250px;" /><br />
            }
        }

        var documents = Model.Location.Attachments.Where(f => f.Type != BFI.Entities.AttachmentType.Image);
        if (documents.Count() > 0) {
            <h3>Documents</h3>
            @foreach (var item in documents) {
                <a href="@string.Format("{0}/{1}_{2}",Model.AttachmentUri, item.Id,item.Name)">@item.Name</a> @item.Description<br />
            }
        }
    }

    <table class="table table-striped table-bordered">
        <tr>
            <td>Name</td>
            <td>@Model.Location.Name</td>
        </tr>
        <tr>
            <td>Type</td>
            <td>@Model.Location.Type.GetDisplayName()</td>
        </tr>
        <tr>
            <td>Address</td>
            <td>@Model.Location.Address</td>
        </tr>
        <tr>
            <td>City</td>
            <td>@Model.Location.City</td>
        </tr>
        <tr>
            <td>State / Province</td>
            <td>@Model.Location.StateProvince</td>
        </tr>
        <tr>
            <td>Post Code</td>
            <td>@Model.Location.PostCode</td>
        </tr>
    </table>
</div>

BFI.WebAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Administration</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">BFI.WebAdmin</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.HasRole("BFI Administrator")) {
                    <li>
                        <a asp-area="" asp-controller="Roles" asp-action="Index" title="Roles">Roles</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Users" asp-action="Index" title="Users">Users</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Companies" asp-action="Index" title="Companies">Companies</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Regions" asp-action="Index" title="Regions">Regions</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Locations" asp-action="Index" title="Locations">Locations</a>
                    </li>
                    }
                    @if (User.HasRole("Company Administrator")) {
                    <li>
                        <a asp-area="" asp-controller="Companies" asp-action="Index" title="My Company">My Company</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Locations" asp-action="Index" title="Locations">My Locations</a>
                    </li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p></p>
        </footer>
    </div>

    <environment include="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>

        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

BFI.WebAdmin/Views/Shared/json.cshtml
<h2>API response</h2>

<pre>@ViewBag.Json</pre>